# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea688554b66299a52fabd94e988c88bb39b15dab8f898c59ed5cf5124ef1e435db222470d9b1c7c9e4f53539cf159ecbea455ffd696412176a07e7c448be4179

test:
  secret_key_base: 95f319fdc3f8f0f01c89635cff92e2d72979266d55c9c69aca35ebb6ee65657457a71dce303c580730563f757cad3d719ee7e9ee452912e31264fe99df9fcecc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
